blog/urls.py
from django.conf.urls import url

from .views import PostListView, PostDetailView, PostArchiveIndexView, PostYearArchiveView, PostMonthArchiveView, \
    PostDayArchiveView, TaggingCloudView, TaggingPostListView, LatestPostFeed

urlpatterns = [
    url(r'^$',
        PostListView.as_view(),
        name='post_index'),

    url(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/$',
        PostDetailView.as_view(),
        name='post_detail'),

    url(r'^archive/$',
        PostArchiveIndexView.as_view(),
        name='post_archive'),
    url(r'^archive/(?P<year>\d{4})/$',
        PostYearArchiveView.as_view(),
        name='post_year_archive'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        PostMonthArchiveView.as_view(month_format='%m'),
        name="post_month_archive"),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        PostDayArchiveView.as_view(month_format='%m'),
        name="post_day_archive"),

    url(r'^tag/$',
        TaggingCloudView.as_view(),
        name='tagging_cloud'),
    url(r'^tag/(?P<tag>[^/]+(?u))/$',
        TaggingPostListView.as_view(),
        name='tagging_post_list'),

    url(r'^feed/$',
        LatestPostFeed(),
        name='post_feed'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from .views import IndexView, UserCreateView, UserCreateDoneTemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^accounts/', include('django.contrib.auth.urls')),  # no namespace!
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTemplateView.as_view(), name='register_done'),

    # Project own apps
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _
from simplemde.fields import SimpleMDEField
from tagging.fields import TagField


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', _('Draft')),
        ('published', _('Published')),
    )

    title = models.CharField(verbose_name=_('Title'), max_length=250)
    slug = models.SlugField(verbose_name=_('Slug'), max_length=250, unique=False, allow_unicode=True)
    author = models.ForeignKey(User, verbose_name=_('Author'), related_name='blog_posts')
    description = models.TextField(verbose_name=_('Description'), blank=True)
    content = SimpleMDEField(verbose_name=_('Content'))
    published = models.DateTimeField(verbose_name=_('Date published'), null=True)
    created = models.DateTimeField(verbose_name=_('Date created'), auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_('Date updated'), auto_now=True)
    status = models.CharField(verbose_name=_('Status'), max_length=10, choices=STATUS_CHOICES, default='draft')
    tag = TagField()

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')
        ordering = ('-published',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.pk, self.slug,))

    def get_previous_post(self):
        previous_post = Post.objects.filter(status='published').filter(id__lt=self.id).order_by('-published').first()

        if previous_post is None:
            return None

        return reverse('blog:post_detail', args=(previous_post.pk, previous_post.slug,))

    def get_next_post(self):
        next_post = Post.objects.filter(status='published').filter(id__gt=self.id).order_by('-published').last()

        if next_post is None:
            return None

        return reverse('blog:post_detail', args=(next_post.pk, next_post.slug,))


class Image(models.Model):
    post = models.ForeignKey(Post, verbose_name=_('Post'), related_name='blog_posts')
    image = models.ImageField(verbose_name=_('Image'), upload_to='img/%Y/%m')
    created = models.DateTimeField(verbose_name=_('Date created'), auto_now_add=True)

    class Meta:
        verbose_name = _('image')
        verbose_name_plural = _('images')
        ordering = ['created']

    def __str__(self):
        return self.image.name

blog/forms.py
from django import forms

from django.utils.translation import ugettext_lazy as _


class PostSearchForm(forms.Form):
    q = forms.CharField(label=_('Search Word'))

blog/views.py
from django.contrib.syndication.views import Feed
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView
from tagging.views import TaggedObjectList

from .models import Post
from .viewmixins import PageableMixin, SearchFormMixin


class PostListView(PageableMixin, SearchFormMixin, ListView):
    context_object_name = 'posts'
    template_name = 'blog/post_list.html'

    def get_queryset(self):
        form = self.form_class(self.request.GET)

        queryset = Post.objects.filter(status='published')

        if form.is_valid():
            q = form.cleaned_data['q']
            queryset = queryset.filter(Q(title__icontains=q) | Q(description__icontains=q) | Q(content__icontains=q))

        queryset = queryset.order_by('-published')

        return queryset


class PostDetailView(SearchFormMixin, DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'


class PostArchiveIndexView(PageableMixin, SearchFormMixin, ArchiveIndexView):
    queryset = Post.objects.filter(status='published').order_by('-published')
    context_object_name = 'posts'
    template_name = 'blog/post_archive.html'
    date_field = 'updated'


class PostYearArchiveView(PageableMixin, SearchFormMixin, YearArchiveView):
    queryset = Post.objects.filter(status='published').order_by('-published')
    context_object_name = 'posts'
    template_name = 'blog/post_archive_year.html'
    date_field = 'updated'
    make_object_list = True


class PostMonthArchiveView(PageableMixin, SearchFormMixin, MonthArchiveView):
    queryset = Post.objects.filter(status='published').order_by('-published')
    context_object_name = 'posts'
    template_name = 'blog/post_archive_month.html'
    date_field = 'updated'


class PostDayArchiveView(PageableMixin, SearchFormMixin, DayArchiveView):
    queryset = Post.objects.filter(status='published').order_by('-published')
    context_object_name = 'posts'
    template_name = 'blog/post_archive_day.html'
    date_field = 'updated'


class TaggingCloudView(SearchFormMixin, TemplateView):
    template_name = 'blog/tagging_cloud.html'


class TaggingPostListView(PageableMixin, SearchFormMixin, TaggedObjectList):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/tagging_post_list.html'


class LatestPostFeed(Feed):
    title = _('Blog Feeds')
    link = '/feed'
    description = _('Blog Recent Posts')

    def items(self):
        return Post.objects.filter(status='published').order_by('-published')[:10]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.description

    def item_link(self, item):
        return reverse('blog:post_detail', args=(item.pk, item.slug,))

conf/views.py
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView


class IndexView(TemplateView):
    template_name = 'index.html'


class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')


class UserCreateDoneTemplateView(TemplateView):
    template_name = 'registration/register_done.html'

templates/blog/blog_base.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            {% block breadcrumb %}{% endblock %}
            {% block entry %}{% endblock %}

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>{% trans 'Blog Search' %}</h4>
                    <form action="{% url 'blog:post_index' %}" method="get" class="input-group">
                        <input id="{{ form.q.id_for_label }}" name="{{ form.q.html_name }}" type="text"
                               class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button"><i class="fa fa-search"></i></button>
                        </span>
                    </form>
                    <!-- /.input-group -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci
                        accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>{% trans 'Blog Categories' %}</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

                <div class="well">
                    <h4>{% trans 'Popular Tags' %}</h4>
                    <div>
                        {% load tagging_tags %}
                        {% tag_cloud_for_model blog.Post as tags with steps=6 min_count=1 distribution=log %}
                        {% for tag in tags %}
                            <a href="{% url 'blog:tagging_post_list' tag.name %}"
                               class="label label-default">{{ tag.name }}</a>&nbsp;
                        {% endfor %}
                    </div>
                </div>

                <!-- Recent Posts Well -->
                <div class="well">
                    <h4>{% trans 'Recent Posts' %}</h4>
                    {% load blog_tags %}
                    <ul>
                        {% recent_posts 5 as posts %}
                        {% for post in posts %}
                            <li><a href="{{ post.get_absolute_url }}">{{ post.title|truncatechars:25 }}</a></li>
                        {% endfor %}
                    </ul>
                </div>

                <!-- Recent Comments Well -->
                <div class="well">
                    <h4>{% trans 'Recent Comments' %}</h4>
                    {% load disqus_tags %}
                    {% disqus_recent_comments %}
                </div>

                <!-- Meta -->
                <div class="well">
                    <h4>{% trans 'Meta' %}</h4>
                    <ul>
                        <li><a href="{% url 'blog:post_archive' %}">{% trans 'Blog Archive' %}</a></li>
                        <li><a href="{% url 'blog:tagging_cloud' %}">{% trans 'Tag Cloud' %}</a></li>
                        <li><a href="{% url 'blog:post_feed' %}">{% trans 'RSS' %}</a></li>
                        {% if user.is_superuser %}
                            <li><a href="{% url 'admin:index' %}">{% trans 'Admin' %}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
{% endblock %}

templates/blog/post_archive.html
{% extends "blog/blog_base.html" %}

{% load i18n %}

{% block title %}{% trans 'Blog Archive' %}{% endblock %}

{% block breadcrumb %}
    <div class="container spacer_30">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">{% trans 'Home' %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:post_index' %}">{% trans 'Blog' %}</a></li>
            <li class="breadcrumb-item active">{% trans 'Blog Archive' %}</li>
        </ol>
    </div>
{% endblock %}

{% block entry %}
    <div class="col-md-8 post">
        <h2>
            {% trans 'Blog Archive' %}
        </h2>
        <hr/>

        <ul>
            {% for date in date_list %}
                <li style="display: inline;">
                    <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">
                        {% blocktrans with year=date|date:'Y' %}Year - {{ year }}{% endblocktrans %}
                    </a>
                </li>
            {% endfor %}
        </ul>
        <hr/>

        <div>
            <ul>
                {% for post in posts %}
                    <li>{{ post.published|date:'Y-m-d' }}&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <!-- Pagination -->
        <div class="text-center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li>
                            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}

                    {% for i in page_range %}
                        {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li>
                            <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}

templates/blog/post_archive_day.html
{% extends "blog/blog_base.html" %}

{% load i18n %}

{% block title %}{% trans 'Blog Archive' %}{% endblock %}

{% block breadcrumb %}
    <div class="container spacer_30">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">{% trans 'Home' %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:post_index' %}">{% trans 'Blog' %}</a></li>
            <li class="breadcrumb-item active">{% trans 'Blog Archive' %}</li>
        </ol>
    </div>
{% endblock %}

{% block entry %}
    <div class="col-md-8 post">
        <h2>{% blocktrans with d=day|date:'N d, Y' %}Daily archive {{ d }}{% endblocktrans %}</h2>
        <hr/>

        <div>
            <ul>
                {% for post in posts %}
                    <li>{{ post.published|date:'Y-m-d' }}&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <hr/>

        <!-- Pagination -->
        <div class="text-center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li>
                            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}

                    {% for i in page_range %}
                        {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li>
                            <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}

templates/blog/post_archive_month.html
{% extends "blog/blog_base.html" %}

{% load i18n %}

{% block title %}{% trans 'Blog Archive' %}{% endblock %}

{% block breadcrumb %}
    <div class="container spacer_30">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">{% trans 'Home' %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:post_index' %}">{% trans 'Blog' %}</a></li>
            <li class="breadcrumb-item active">{% trans 'Blog Archive' %}</li>
        </ol>
    </div>
{% endblock %}

{% block entry %}
    <div class="col-md-8 post">
        <h2>{% blocktrans with m=month|date:'N, Y' %}Monthly archive {{ m }}{% endblocktrans %}</h2>
        <hr/>

        <ul>
            {% for date in date_list %}
                <li style="display: inline;">
                    <a href="{% url 'blog:post_day_archive' date|date:'Y' date|date:'m' date|date:'d' %}">{{ date|date:'d' }}</a>
                </li>
            {% endfor %}
        </ul>
        <hr/>

        <div>
            <ul>
                {% for post in posts %}
                    <li>{{ post.published|date:'Y-m-d' }}&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <!-- Pagination -->
        <div class="text-center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li>
                            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}

                    {% for i in page_range %}
                        {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li>
                            <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}

templates/blog/post_archive_year.html
{% extends "blog/blog_base.html" %}

{% load i18n %}

{% block title %}{% trans 'Blog Archive' %}{% endblock %}

{% block breadcrumb %}
    <div class="container spacer_30">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">{% trans 'Home' %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:post_index' %}">{% trans 'Blog' %}</a></li>
            <li class="breadcrumb-item active">{% trans 'Blog Archive' %}</li>
        </ol>
    </div>
{% endblock %}

{% block entry %}
    <div class="col-md-8 post">
        <h2>{% blocktrans with y=year|date:'Y' %}Yearly archive {{ y }}{% endblocktrans %}</h2>
        <hr/>

        <ul>
            {% for date in date_list %}
                <li style="display: inline;">
                    <a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'m' %}">{{ date|date:'F' }}</a>
                </li>
            {% endfor %}
        </ul>
        <hr/>

        <div>
            <ul>
                {% for post in posts %}
                    <li>{{ post.published|date:'Y-m-d' }}&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <!-- Pagination -->
        <div class="text-center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li>
                            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}

                    {% for i in page_range %}
                        {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li>
                            <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}

templates/blog/post_detail.html
{% extends "blog/blog_base.html" %}

{% load i18n %}

{% block title %}{{ post.title }}{% endblock %}

{% block breadcrumb %}
    <div class="container spacer_30">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">{% trans 'Home' %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:post_index' %}">{% trans 'Blog' %}</a></li>
            <li class="breadcrumb-item active">{{ post.title }}</li>
        </ol>
    </div>
{% endblock %}

{% block entry %}
    <!-- Blog Entries Column -->
    <div class="col-md-8">

        <!-- Blog Entry -->
        <div class="row">
            <div class="col-md-12">
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-12">
                <p></p>
                <p>
                    <i class="fa fa-user"></i> <a href="#">{{ post.author }}</a>
                    | <i class="fa fa-calendar"></i> {{ post.published|date:"Y-m-d H:m" }}
                    | <i class="fa fa-comment"></i> <a href="#">3 Comments</a>
                    | <i class="fa fa-share"></i> <a href="#">39 Shares</a>
                    {% if user.is_superuser %}
                        | <i class="fa fa-edit"></i> <a href="{% url 'admin:blog_post_change' post.id %}">Edit</a>
                    {% endif %}
                </p>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-12 post">
                {% load blog_filters %}
                {{ post.content|markdownify }}
            </div>
        </div>
        <hr/>
        <!-- tags -->
        {% load tagging_tags %}
        <div class="panel-footer">
            {% tags_for_object post as tags %}
            {% for tag in tags %}
                <a href="{% url 'blog:tagging_post_list' tag.name %}">
                    <span class="label label-default">{{ tag.name }}</span>
                </a>
            {% empty %}
                <span>&nbsp;</span>
            {% endfor %}
        </div>
        <hr/>

        <!-- Pager -->
        <ul class="pager">
            {% with post.get_previous_post as previous_post %}
                {% if previous_post %}
                    <li class="next"><a href="{{ previous_post }}">{% trans 'Older &rarr;' %}</a></li>
                {% else %}
                    <li class="next disabled"><a href="#">{% trans 'Older &rarr;' %}</a></li>
                {% endif %}
            {% endwith %}

            {% with post.get_next_post as next_post %}
                {% if next_post %}
                    <li class="previous">
                        <a href="{{ post.get_next_post }}">{% trans '&larr; Newer' %}</a>
                    </li>
                {% else %}
                    <li class="previous disabled">
                        <a href="#">{% trans '&larr; Newer' %}</a>
                    </li>
                {% endif %}
            {% endwith %}
        </ul>

        <!-- Disqus Comments -->
        {% load disqus_tags %}
        {% disqus_show_comments %}
    </div>
{% endblock %}

templates/blog/tagging_cloud.html
{% extends "blog/blog_base.html" %}

{% load i18n %}

{% block title %}{% trans 'Tag Cloud' %}{% endblock %}

{% block breadcrumb %}
    <div class="container spacer_30">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">{% trans 'Home' %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:post_index' %}">{% trans 'Blog' %}</a></li>
            <li class="breadcrumb-item active">{% trans 'Tag Cloud' %}</li>
        </ol>
    </div>
{% endblock %}

{% block entry %}
    <!-- Tags Column -->
    <div class="col-md-8">
        {% load tagging_tags %}
        {% tag_cloud_for_model blog.Post as tags with steps=6 min_count=1 distribution=log %}
        {% for tag in tags %}
            <a href="{% url 'blog:tagging_post_list' tag.name %}" class="btn btn-default">
                {{ tag.name }} <span class="badge">{{ tag.font_size }}</span>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/blog/tagging_post_list.html
{% extends "blog/blog_base.html" %}

{% load i18n %}

{% block title %}{% trans 'Blog Archive' %}{% endblock %}

{% block breadcrumb %}
    <div class="container spacer_30">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">{% trans 'Home' %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:post_index' %}">{% trans 'Blog' %}</a></li>
            <li class="breadcrumb-item active">{% trans 'Post List by Tag' %}</li>
        </ol>
    </div>
{% endblock %}

{% block entry %}
    <div class="col-md-8 post">
        <h2>
            {% trans 'Post List by Tag' %} - {{ tag.name }}
        </h2>
        <hr/>

        <div>
            <ul>
                {% for post in posts %}
                    <li>{{ post.published|date:'Y-m-d' }}&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <!-- Pagination -->
        <div class="text-center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li>
                            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}

                    {% for i in page_range %}
                        {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li>
                            <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}